# Generated by Django 4.1.7 on 2023-04-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubs',
            name='picture',
            field=models.ImageField(upload_to='profile_pics/{username}/'),
        ),
    ]
