# Generated by Django 4.1.7 on 2023-04-16 02:58

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_pubs_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubs',
            name='username',
            field=models.CharField(default='anonymous', max_length=50),
        ),
        migrations.AlterField(
            model_name='pubs',
            name='picture',
            field=models.ImageField(upload_to=blogs.models.get_image_upload_path),
        ),
    ]
