# Generated by Django 4.1.7 on 2023-04-16 03:14

import blogs.models
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_pubs_username_alter_pubs_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubs',
            name='url_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pubs',
            name='picture',
            field=models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=blogs.models.get_image_upload_path),
        ),
    ]
