# Generated by Django 4.1.7 on 2023-04-16 03:36

import blogs.models
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_pubs_url_img_alter_pubs_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_carrera', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=255)),
                ('foto_perfil', models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=blogs.models.get_image_upload_path)),
                ('strikes', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.carrera')),
            ],
        ),
    ]
