# Generated by Django 4.1.7 on 2023-04-16 10:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_usuario_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
